### ISSUE TITLE
[Enhancement] Footer permanent placement

### ISSUE THREAD

**Issue by Dux02** [Proteus-Eretes/hswi2#119]
Op het moment als je in velden dingen gaat aanvinken dan komt de footer ineens in view. Is niet zo nice, msch vast aan de onderkant plakken zodat je hem altijd ziet. Dit is ook nice m altijd het IRIS logo te laten zien voor een beetje brand awareness.

**Comment by Gerbuuun** [comment]
De footer doet precies wat het moet doen. (Beneden alle content)
Anders zit de footer constant in beeld (neemt ruimte in) terwijl dit niet nodig is
