### ISSUE TITLE
[BUG] Regatta index pagina laadt niet de eerste keer

### ISSUE THREAD

**Issue by Gerbuuun** [Proteus-Eretes/hswi2#12]
**Beschrijving van de bug**
Als je vanaf de index pagina op een regatta klikt, laadt hij het eerst niet.
Pas als je de pagina herlaadt, wordt de pagina goed weergeven.

**Om na te doen**
Stappen om de zelfde bug te krijgen:
1. Ga naar de index pagina
2. Zoek een regatta op
3. Klik er op
4. Zie dat de pagina niet laadt

**Wat er zou moeten gebeuren**
De pagina moet de eerste keer al geladen worden.

**Comment by cornelis1998** [comment]
changed nuxt link to a tag
