### ISSUE TITLE
[BUG] clubpagina loaded twice

### ISSUE THREAD

**Issue by cornelis1998** [Proteus-Eretes/hswi2#63]
**Beschrijving van de bug**
When loading the club page it loads the previous club, then quickly replaces it with the correct club

**Om na te doen**
Stappen om de zelfde bug te krijgen:
1. load a club page(ex. Gyas)
2. go back to club overview
3. select another club(ex. Proteus)

**Wat er zou moeten gebeuren**
Directly load the club page without flash of the previous club
probably caused by the await club.selectByURL, but this was the easiest fix for a more import bug

**Comment by Gerbuuun** [comment]
Deze is ook gefixt in #71
