### ISSUE TITLE
[BUG] refresh field not working

### ISSUE THREAD

**Issue by cornelis1998** [Proteus-Eretes/hswi2#76]
**Beschrijving van de bug**
wanneer je een veld geladen hebt en de pagina ververst word de data niet geladen
zelfde geldt voor wanneer je de uitslagen laad en herlaad

**Om na te doen**
Stappen om de zelfde bug te krijgen:
1. Ga naar een wedstrijd
2. Klik op een veld
3. ververs de pagina

**Wat er zou moeten gebeuren**
Wanneer je ververst moet de data geladen worden

**Comment by Gerbuuun** [comment]
In #71 dit is gefixt, is het tijd om over te stappen naar ssr? Als de db is overgezet kunnen we dan gelijk ook de api in dit project bouwen...
